# Action's main info
name: "Khoi Packj Security Audit"
description: 'Use Packj to avoid malicious and other "risky" open-source software dependencies'

# Action's author name
author: "Ossillate, Inc."

# Action's branding data for GitHub Marketplace
branding:
  icon: "package" # icon name from Feather open source icons pack
  color: "orange"

inputs:
  DEPENDENCY_FILES:
    description: A string params passed to Packj for auditing
    required: true
  REPO_TOKEN:
    description: Your repo GITHUB_TOKEN
    required: true

runs:
  using: "composite"

  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup Python & pip
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: pip

    - name: Clone Packj repo
      shell: bash
      run: git clone https://github.com/ossillate-inc/packj

    - name: Create virtual environment
      shell: bash
      run: python3 -m venv venv

    - name: Activate virtual environment
      shell: bash
      run: source venv/bin/activate

    - name: Install Packj's dependencies
      shell: bash
      run: pip3 install -r ./packj/requirements.txt

    - name: Auditing deps with Packj
      shell: bash
      run: python3 ./packj/main.py audit -f ${{ inputs.DEPENDENCY_FILES }}

    - name: Analyze audit report
      shell: bash
      run: |
        echo "BODY<<EOF" >> $GITHUB_ENV
        if [ -f /tmp/packj_audit_*/*.html ]; then
          html_report=$(ls /tmp/packj_audit_*/*.html)
          cat $html_report | head -n -2 | tail -n +10 | sed 's/^[\s\t\r]*//g' >> $GITHUB_ENV
        else
          echo "<h4>Failed to perform Packj audit! Refer to workflow run for details</h4>" >> /$GITHUB_ENV
        fi
        run_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        commit_link="${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
        echo "Triggered by <a href=$run_url>workflow run ${{ github.run_number }}</a> on commit <a href=$commit_link>${{ github.sha }}</a>"  >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        echo "TITLE=Packj audit found risky dependencies!" >> $GITHUB_ENV

    - name: create issue if ISSUE_REQUIRED is set
      if: ${{ github.head_ref == '' }}
      uses: rishabhgupta/git-action-issue@v2
      with:
        token: ${{ inputs.REPO_TOKEN }}
        title: ${{ env.TITLE }}
        body: ${{ env.BODY }}

    - name: Comment PR
      if: ${{ github.head_ref }}
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: ${{ env.BODY }}
        GITHUB_TOKEN: ${{ inputs.REPO_TOKEN }}
